name: deploy
on:
    push:
    workflow_dispatch:
    schedule:
        # Runs everyday at 8:00 AM [ 0 8 * * *]
        - cron: "0 0 * * *"
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true
            - name: Build Web
              # run: hugo
              run: hugo --minify
            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              with:
                  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
                  EXTERNAL_REPOSITORY: mpv945/xiehaijun-blog
                  PUBLISH_BRANCH: main
                  PUBLISH_DIR: ./public
                  force_orphan: true
                  CNAME: xiehaijun.ewancle.com
                  commit_message: ${{ github.event.head_commit.message }}
    async-gitee:
        runs-on: ubuntu-latest
        needs: build-and-deploy
        steps:
            - name: Sync to Gitee
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
              with:
                  source-repo: git@github.com:mpv945/xiehaijun-blog.git
                  #destination-repo: git@gitee.com:mpv945/xiehaijun-blog.git
                  destination-repo: git@gitee.com:mpv945/mpv945.git
            - name: Build Gitee Pages
              uses: yanglbme/gitee-pages-action@main
              with:
                  gitee-username: mpv945
                  gitee-password: ${{ secrets.GITEE_PASSWORD }}
                  gitee-repo: mpv945/mpv945
                  branch: master
                  https: true
