name: success-notifications-ci
on:
  workflow_run: # 依赖别的工作流运行：https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#workflow_run
    workflows: [blog-ci]
    types:
      - completed # 依赖别的工作流完成了
jobs:
  run-notifications:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # 依赖的工作流运行成功，才执行
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master # 拉取master分支代码，推送到master
      - run: |
          TZ=Asia/Shanghai date "+%Y-%m-%d-%H_%M_%S-%A" > generated.txt
          git config user.name mpv945
          git config user.email zhenxindefeng@126.com
          git add generated.txt
          git commit -m "$(TZ=Asia/Shanghai date "+%Y-%m-%d-%H_%M_%S-%A") master自动部署完成，通知流处理提交的更新。[跳过的自动化提交]"
          git push